#:kivy 2.0.0

<BotonImagen@ButtonBehavior+Image>:
    source: ""
    size_hint: None, None
    size: dp(40), dp(50)

<BotonRecarga>:
    orientation: 'vertical'
    spacing: dp(10)
    padding: [dp(10), dp(20), dp(10), dp(10)]
    size_hint: None, None
    size: (dp(150), dp(150))
    canvas.before:
        Color:
            rgba: 0.121, 0.247, 0.376, 1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(15),]
        Color:
            rgba: (0.137, 0.455, 0.796, 1) if self.seleccionado else (0, 0, 0, 0)
        Line:
            width: 4
            rectangle: (self.x, self.y, self.width, self.height)
    Image:
        source: root.img_src
        size_hint: None, None
        size: dp(90), dp(90)  # Cambiado a dp
        pos_hint: {"center_x": 0.5, "top": 1}  # Centrado total para imagen
    Label:
        text: root.text_btn
        font_name: 'Intro'
        font_size: sp(24)  # Cambiado a sp para texto
        color: (1, 1, 1, 1)
        size_hint_y: None
        height: self.texture_size[1]
        halign: "center"
        valign: "middle"
        text_size: self.width, None

<BotonVolver@ButtonBehavior+BoxLayout>:
    orientation: 'horizontal'
    spacing: dp(8)  # Cambiado a dp
    size_hint: None, None
    size: dp(120), dp(40)  # Cambiado a dp
    padding: 0
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0  # Fondo transparente
        Rectangle:
            pos: self.pos
            size: self.size
    Image:
        source: "images/volver.png"
        size_hint: None, None
        size: dp(50), dp(50)  # Cambiado a dp

<BotonContinuar@ButtonBehavior+BoxLayout>:
    orientation: 'horizontal'
    spacing: dp(8)  # Cambiado a dp
    size_hint: None, None
    size: dp(180), dp(50)  # Cambiado a dp
    padding: 0
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0  # Fondo transparente
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        text: "Continuar"
        font_name: 'Intro'
        font_size: sp(20)  # Cambiado a sp
        color: (0.110, 0.235, 0.392)
        size_hint_x: None
        width: dp(140)  # Cambiado a dp
        halign: "left"
        valign: "middle"
        text_size: self.size
    Image:
        source: "images/continuar.png"
        size_hint: None, None
        size: dp(50), dp(50)  # Cambiado a dp

<BotonOperacion>:
    orientation: 'vertical'
    spacing: dp(10)  # Cambiado a dp
    padding: [dp(10), dp(20), dp(10), dp(10)]  # Cambiado a dp
    size_hint: None, None
    size: (dp(50), dp(50))  # Cambiado a dp
    Image:
        source: root.img_src
        size_hint: None, None
        size: dp(50), dp(50)  # Cambiado a dp
        pos_hint: {"center_x": 0.5, "center_y": 0.6}

<BotonPapelera@ButtonBehavior+Image>:
    source: "images/papelera.png"
    size_hint: None, None
    size: dp(50), dp(50)  # Cambiado a dp

<MyRoundedButton@Button>:
    background_normal: ""
    background_color: 0, 0, 0, 0
    canvas.before:
        Color:
            rgba: 0.121, 0.247, 0.376, 1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(20),]  # Cambiado a dp

<ButtonBehavior+Image>:
    source: "images/papelera.png"
    allow_stretch: True
    keep_ratio: True


<CarritoItem>:
    size_hint_y: None
    height: dp(60)  # Cambiado a dp

    BoxLayout:
        orientation: 'horizontal'
        spacing: dp(10)  # Cambiado a dp
        padding: [dp(10), dp(5)]  # Cambiado a dp

        Label:
            id: label_descripcion
            text: "Botellón X L"
            font_name: 'Intro'
            font_size: sp(22)  # Cambiado a sp
            color: 0,0,0,1
            halign: "left"
            valign: "middle"
            text_size: (self.width, self.height)
            size_hint_x: 0.35

        # Contenedor de cantidad
        BoxLayout:
            orientation: 'horizontal'
            spacing: dp(5)  # Cambiado a dp
            size_hint_x: 0.35

            BotonOperacion:
                img_src: "images/menos.png"
                size_hint: None, None
                size: dp(40), dp(40)  # Cambiado a dp
                on_press: root.disminuir_cantidad()

            Label:
                id: label_cantidad
                text: str(root.cantidad)
                font_name: 'Intro'
                font_size: sp(22)  # Cambiado a sp
                color: 0,0,0,1
                size_hint: None, None
                size: dp(40), dp(40)  # Cambiado a dp
                halign: "center"
                valign: "middle"
                text_size: (self.width, self.height)

            BotonOperacion:
                img_src: "images/mas.png"
                size_hint: None, None
                size: dp(40), dp(40)  # Cambiado a dp
                on_press: root.aumentar_cantidad()
                
        Label:
            id: label_total
            text: f"Bs {root.total}"
            font_name: 'Intro'
            font_size: sp(22)  # Cambiado a sp
            color: 0,0,0,1
            size_hint_x: 0.25
            halign: "center"
            valign: "middle"
            text_size: (self.width, self.height)
            
        BotonOperacion:
            img_src: "images/papelera.png"
            size_hint: None, None
            size: dp(40), dp(40)  # Cambiado a dp
            on_press: root.eliminar_producto()
         
<GestorPantallas>:
    PantallaInicio:
    PantallaRecarga:
    PantallaInformacion:
    PantallaContacto:
    PantallaLogin:
    PantallaCarrito:
    PantallaPago:

<PantallaInicio>:
    name: "inicio"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                source: "images/fondo.png"
                pos: self.pos
                size: self.size

        Image:
            source: "images/logo-inicio.png"
            size_hint: (0.8, 0.6)  # Ya está en proporciones relativas (correcto)
            pos_hint: {"center_x": 0.5, "top": 0.95}

        MyRoundedButton:
            text: "RECARGAR"
            font_name: 'Intro'
            font_size: sp(36)  # Cambiado a sp
            size_hint: (0.3, 0.15)  # Correcto (proporciones relativas)
            pos_hint: {"center_x": 0.5, "y": 0.2}
            color: (1, 1, 1, 1)
            on_press:
                app.root.current = "recarga"

        BotonImagen:
            id: superusuario
            source: "images/superusuario.png"
            pos_hint: {"right": 0.98, "top": 0.98}
            on_press: print("Superusuario")
            opacity: 0 #oculto al principio

        BotonImagen:
            source: "images/info.png"
            on_press: app.root.current = "informacion"
            pos_hint: {"x": 0.02, "y": 0.02}

        BotonImagen:
            source: "images/contacto.png"
            on_press: app.root.current = "contacto"
            pos_hint: {"right": 0.98, "y": 0.02}


<PantallaRecarga>:
    name: "recarga"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                source: "images/fondo.png"
                pos: self.pos
                size: self.size

        Label:
            text: "Seleccione la capacidad del botellón"
            font_name: 'Intro'
            font_size: sp(26)  # Cambiado a sp
            color: (0.110, 0.235, 0.392)
            size_hint: None, None
            size: self.texture_size
            pos_hint: {"center_x": 0.5, "top": 0.85}

        BotonImagen:
            id: carrito
            source: "images/carrito.png"
            size: dp(90), dp(70)  # Cambiado a dp
            pos_hint: {"right": 0.98, "top": 0.98}
            on_press:
                app.root.current = "carrito"

        # BOTONES PRODUCTOS  
        GridLayout:
            id: grid_botones
            cols: 5
            spacing: dp(30)  # Cambiado a dp
            size_hint: None, None
            size: dp(870), dp(150)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "center_y": 0.6}
            padding: 0

            BotonRecarga:
                img_src: "images/icono_1.png"
                text_btn: "1 Litro"
                pantalla_recarga: root
                on_press: root.seleccionar_producto(4)

            BotonRecarga:
                img_src: "images/icono_2.png"
                text_btn: "2 Litros"
                pantalla_recarga: root
                on_press: root.seleccionar_producto(3)

            BotonRecarga:
                img_src: "images/icono_5.png"
                text_btn: "5 Litros"
                pantalla_recarga: root
                on_press: root.seleccionar_producto(2)

            BotonRecarga:
                img_src: "images/icono_20.png"
                text_btn: "10 Litros"
                pantalla_recarga: root
                on_press: root.seleccionar_producto(1)

            BotonRecarga:
                img_src: "images/icono_10.png"
                text_btn: "19 Litros"
                pantalla_recarga: root
                on_press: root.seleccionar_producto(0)
        
        # CONTROLES CANTIDAD
        GridLayout:
            cols: 5
            spacing: dp(50)  # Cambiado a dp
            padding: dp(20)  # Cambiado a dp
            size_hint: None, None
            size: dp(870), dp(70)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "y": 0.32}

            Widget:

            BotonOperacion:
                img_src: "images/menos.png"
                on_press: root.decrementar_cantidad()

            Label:
                id: cantidad_label
                text: str(root.cantidad)
                font_size: sp(28)  # Cambiado a sp
                size_hint: None, None
                size: dp(70), dp(60)  # Cambiado a dp
                color: 0, 0, 0, 1
                canvas.before:
                    Color:
                        rgba: 0.9, 0.9, 0.9, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(15),]  # Cambiado a dp

            BotonOperacion:
                img_src: "images/mas.png"
                on_press: root.incrementar_cantidad()

            Widget:
        
        #BOTON AGREGAR
        GridLayout:
            cols: 5
            spacing: dp(50)  # Cambiado a dp
            padding: dp(20)  # Cambiado a dp
            size_hint: None, None
            size: dp(870), dp(70)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "y": 0.18}

            Widget:
            Widget:

            Button:
                text: "AÑADIR"
                font_name: 'Intro'
                font_size: sp(22)  # Cambiado a sp
                size_hint: None, None
                size: dp(120), dp(60)  # Cambiado a dp
                background_normal: ""
                background_color: 0, 0, 0, 0
                color: 1, 1, 1, 1
                canvas.before:
                    Color:
                        rgba: (0.027, 0.294, 0.541, 1) 
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(15),]  # Cambiado a dp
                on_press: root.agregar_al_carrito()

            Widget:
            Widget:
        
        BotonVolver:
            pos_hint: {"x": 0.03, "y": 0.032}
            on_press: app.root.current = "inicio"

    BoxLayout:
        orientation: 'vertical'
        size_hint: None, None
        size: (dp(300), dp(110))  # Cambiado a dp
        pos_hint: {'right': 0.65, 'y': 0.02}
        spacing: dp(8)  # Cambiado a dp

        Label:
            text: "Precio: ${} Bs".format(app.PRODUCTS[root.producto_seleccionado].precio)
            font_name: 'Intro'
            font_size: sp(18)  # Cambiado a sp
            color: (1.0, 1.0, 1.0)
            size_hint_y: None
            height: dp(40)  # Cambiado a dp

    BotonContinuar:
        size_hint_y: None
        height: dp(50)  # Cambiado a dp
        pos_hint: {'right': 0.95, 'y': 0.03}
        on_press: app.root.current = "carrito"

    #POPUP TEMPORAL (NOTIFICACION CARRITO)
    FloatLayout:
        size_hint: 1, 1
        BoxLayout:
            id: popup_label
            size_hint: None, None
            size: dp(400), dp(130)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            orientation: "vertical"
            spacing: dp(5)  # Cambiado a dp
            padding: [dp(20), dp(15)]  # Cambiado a dp
            opacity: 0
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 0.7
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(20),]  # Cambiado a dp

            Image:
                source: "images/check.png" 
                size_hint: None, None
                size: dp(40), dp(40)  # Cambiado a dp
                pos_hint: {"center_x": 0.5}

            Label:
                text: "¡Producto agregado al carrito!"
                font_size: sp(20)  # Cambiado a sp
                font_name: 'Intro'
                color: 1, 1, 1, 1
                halign: "center"
                valign: "middle"
                text_size: self.size


<PantallaInformacion>:
    name: "informacion"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Image:
            source: "images/logo.png"
            size_hint: None, None
            size: dp(120), dp(100)  # Cambiado a dp
            pos_hint: {"x": 0.02, "top": 0.98}

        BoxLayout:
            orientation: "vertical"
            size_hint: 0.8, None
            height: self.minimum_height
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            Label:
                text: "Esta es una expendedora automatizada de agua.\nGracias por preferirnos."
                font_name: 'Intro'
                font_size: sp(24)  # Cambiado a sp
                halign: "center" 
                valign: "middle"
                color: 0, 0, 0, 1
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

        BotonVolver:
            pos_hint: {"x": 0.03, "y": 0.032}
            on_press:
                app.root.current = "inicio"

<PantallaContacto>:
    name: "contacto"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Image:
            source: "images/logo.png"
            size_hint: None, None
            size: dp(120), dp(100)  # Cambiado a dp
            pos_hint: {"x": 0.02, "top": 0.98}

        BoxLayout:
            orientation: "vertical"
            spacing: dp(10)  # Cambiado a dp
            size_hint: None, None
            size: dp(400), dp(300)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "center_y": 0.5}

            Image:
                source: "images/instagram.png"
                size_hint_y: None
                height: dp(50)  # Cambiado a dp
            Label:
                text: "Instagram: @example"
                font_name: 'Intro'
                font_size: sp(20)  # Cambiado a sp
                color: 0, 0, 0, 1

            Image:
                source: "images/correo.png"
                size_hint_y: None
                height: dp(50)  # Cambiado a dp
            Label:
                text: "Correo: example@example.com"
                font_name: 'Intro'
                font_size: sp(20)  # Cambiado a sp
                color: 0, 0, 0, 1

            Image:
                source: "images/telefono.png"
                size_hint_y: None
                height: dp(50)  # Cambiado a dp
            Label:
                text: "Teléfono: +1 234 567 890"
                font_name: 'Intro'
                font_size: sp(20)  # Cambiado a sp
                color: 0, 0, 0, 1

            Image:
                source: "images/whatsapp.png"
                size_hint_y: None
                height: dp(50)  # Cambiado a dp
            Label:
                text: "WhatsApp: +1 987 654 321"
                font_name: 'Intro'
                font_size: sp(20)  # Cambiado a sp
                color: 0, 0, 0, 1

        BotonVolver:
            pos_hint: {"x": 0.03, "y": 0.032}
            on_press:
                app.root.current = "inicio"


<PantallaLogin>:
    name: "login"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Image:
            source: "images/logo.png"
            size_hint: None, None
            size: dp(120), dp(100)  # Cambiado a dp
            pos_hint: {"x": 0.02, "top": 0.98}

        Image:
            source: "images/superusuario.png"
            size_hint: None, None
            size: dp(100), dp(100)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "top": 0.75}

        Label:
            text: "Modo Administrador"
            font_name: 'Intro'
            font_size: sp(28)  # Cambiado a sp
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.5, "top": 0.55}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: input_password
            password: True
            hint_text: "Contraseña"
            size_hint: None, None
            size: dp(300), dp(50)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "center_y": 0.42}
            font_name: 'Intro'
            font_size: sp(22)  # Cambiado a sp
            multiline: False

        Button:
            text: "Ingresar"
            font_name: 'Intro'
            font_size: sp(22)  # Cambiado a sp
            size_hint: None, None
            size: dp(300), dp(50)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "center_y": 0.32}
            background_normal: ""
            background_color: (0.121, 0.247, 0.376, 1)
            color: 1, 1, 1, 1
            on_press: root.verificar_contraseña()

        Label:
            id: etiqueta_status
            text: ""
            font_name: 'Intro'
            font_size: sp(18)  # Cambiado a sp
            color: (1, 0, 0, 1)
            pos_hint: {"center_x": 0.5, "center_y": 0.18}
            size_hint: None, None
            size: self.texture_size

        BotonVolver:
            pos_hint: {"x": 0.03, "y": 0.032}
            on_press:
                app.root.current = "inicio"


<PantallaCarrito>:
    name: "carrito"
    id: carrito_screen

    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                source: "images/fondo.png"
                pos: self.pos
                size: self.size

        # Título
        Label:
            text: "CARRITO DE COMPRA"
            font_name: 'Intro'
            font_size: sp(28)  # Cambiado a sp
            color: (0.110, 0.235, 0.392)
            size_hint: None, None
            size: self.texture_size
            pos_hint: {"center_x": 0.5, "top": 0.90}

        #Contenedor principal
        BoxLayout:
            orientation: 'vertical'
            size_hint: None, None
            size: self.parent.width * 0.5, self.parent.height * 0.6
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            padding: dp(5)  # Cambiado a dp
            spacing: dp(5)  # Cambiado a dp

            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(20),]  # Cambiado a dp
                Color:
                    rgba: app.azul_oscuro
                Line:
                    width: dp(1.8)  # Cambiado a dp
                    rounded_rectangle: (self.x, self.y, self.width, self.height, dp(20))  # Cambiado a dp

            #Encabezado de columnas
            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: None
                height: dp(30)  # Cambiado a dp
                spacing: dp(2)  # Cambiado a dp
                padding: [dp(10), 0, dp(10), 0]  # Cambiado a dp

                Label:
                    text: "PRODUCTO"
                    font_name: 'Intro'
                    font_size: sp(18)  # Cambiado a sp
                    color: 0, 0, 0, 1
                    bold: True
                    size_hint_x: 0.5
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    text: "CANTIDAD"
                    font_name: 'Intro'
                    font_size: sp(18)  # Cambiado a sp
                    color: 0, 0, 0, 1
                    bold: True
                    size_hint_x: 0.5
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    text: "MONTO"
                    font_name: 'Intro'
                    font_size: sp(18)  # Cambiado a sp
                    color: 0, 0, 0, 1
                    bold: True
                    size_hint_x: 0.35
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    text: ""
                    size_hint_x: 0.05
            
            #Divisor azul
            BoxLayout:
                size_hint_y: None
                height: dp(2)  # Cambiado a dp
                canvas.before:
                    Color:
                        rgba: app.azul_oscuro
                    Rectangle:
                        pos: self.pos
                        size: self.size

            # ScrollView con los CarritoItem
            ScrollView:
                size_hint_y: 1
                bar_width: dp(10)  # Cambiado a dp
                scroll_type: ['bars', 'content']
                do_scroll_x: False  

                GridLayout:
                    id: contenedor_items
                    cols: 1
                    spacing: dp(5)  # Cambiado a dp
                    padding: [dp(5), dp(5)]  # Cambiado a dp
                    size_hint_y: None
                    height: self.minimum_height
                    size_hint_x: 1
            
            #Divisor azul entre items y total
            BoxLayout:
                size_hint_y: None
                height: dp(2)  # Cambiado a dp
                canvas.before:
                    Color:
                        rgba: app.azul_oscuro
                    Rectangle:
                        pos: self.pos
                        size: self.size

            BoxLayout:
                size_hint_y: None
                height: dp(40)  # Cambiado a dp
                padding: [dp(10), 0, dp(10), 0]  # Cambiado a dp
                spacing: dp(10)  # Cambiado a dp

                Label:
                    text: "Total:"
                    font_name: 'Intro'
                    font_size: sp(18)  # Cambiado a sp
                    color: 0, 0, 0, 1
                    bold: True
                    halign: "left"
                    valign: "middle"
                    size_hint_x: 0.7
                    text_size: self.size

                Label:
                    id: total_label
                    text: "$0"
                    font_name: 'Intro'
                    font_size: sp(18)  # Cambiado a sp
                    color: 0, 0, 0, 1
                    halign: "right"
                    valign: "middle"
                    size_hint_x: 0.3
                    text_size: self.size

        MyRoundedButton:
            text: "PAGAR"
            font_name: 'Intro'
            font_size: sp(36)  # Cambiado a sp
            size_hint: (0.25, 0.10)
            pos_hint: {"center_x": 0.5, "y": 0.05}
            color: (1, 1, 1, 1)
            on_press: app.root.current = "pago"

        # Botón volver
        BotonVolver:
            pos_hint: {"x": 0.03, "y": 0.032}
            on_press: app.root.current = "recarga"

            
<PantallaPago>:
    name: "pago"
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1  # Blanco
        Rectangle:
            pos: self.pos
            size: self.size

    FloatLayout:
        