#:kivy 2.0.0


<BotonImagen@ButtonBehavior+Image>:
    source: ""
    size_hint: None, None
    size: dp(60), dp(50)

<BotonRecarga>:
    orientation: 'vertical'
    spacing: dp(10)
    padding: [dp(10), dp(20), dp(10), dp(10)]
    size_hint: None, None
    size: (dp(155), dp(155))
    canvas.before:
        Color:
            rgba: 0.121, 0.247, 0.376, 1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(15),]
        Color:
            rgba: (0.137, 0.455, 0.796, 1) if self.seleccionado else (0, 0, 0, 0)
        Line:
            width: 4
            rectangle: (self.x, self.y, self.width, self.height)
    Image:
        source: root.img_src
        size_hint: None, None
        size: dp(90), dp(90)  # Cambiado a dp
        pos_hint: {"center_x": 0.5, "top": 1}  # Centrado total para imagen
    Label:
        text: root.text_btn
        font_name: 'Intro'
        font_size: sp(22)  # Cambiado a sp para texto
        color: (1, 1, 1, 1)
        size_hint_y: None
        height: self.texture_size[1]
        halign: "center"
        valign: "middle"
        text_size: self.width, None

<BotonVolver@ButtonBehavior+BoxLayout>:
    orientation: 'horizontal'
    spacing: dp(8)  # Cambiado a dp
    size_hint: None, None
    size: dp(120), dp(40)  # Cambiado a dp
    padding: 0
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0  # Fondo transparente
        Rectangle:
            pos: self.pos
            size: self.size
    Image:
        source: "images/volver.png"
        size_hint: None, None
        size: dp(50), dp(50)  # Cambiado a dp

<BotonContinuar@ButtonBehavior+BoxLayout>:
    orientation: 'horizontal'
    spacing: dp(8)  # Cambiado a dp
    size_hint: None, None
    size: dp(180), dp(50)  # Cambiado a dp
    padding: 0
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0  # Fondo transparente
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        text: "Continuar"
        font_name: 'Intro'
        font_size: sp(20)  # Cambiado a sp
        color: (0.110, 0.235, 0.392)
        size_hint_x: None
        width: dp(140)  # Cambiado a dp
        halign: "left"
        valign: "middle"
        text_size: self.size
    Image:
        source: "images/continuar.png"
        size_hint: None, None
        size: dp(50), dp(50)  # Cambiado a dp

<BotonOperacion>:
    orientation: 'vertical'
    spacing: dp(10)  # Cambiado a dp
    padding: [dp(10), dp(20), dp(10), dp(10)]  # Cambiado a dp
    size_hint: None, None
    size: (dp(50), dp(50))  # Cambiado a dp
    Image:
        source: root.img_src
        size_hint: None, None
        size: dp(50), dp(50)  # Cambiado a dp
        pos_hint: {"center_x": 0.5, "center_y": 0.6}

<BotonOperacion2>:
    orientation: 'vertical'
    spacing: dp(6)
    padding: [dp(6), dp(12), dp(6), dp(6)]
    size_hint: None, None
    size: (dp(32), dp(32))
    Image:
        source: root.img_src
        size_hint: None, None
        size: dp(35), dp(35)
        pos_hint: {"center_x": 0.5, "center_y": 0.6}


<BotonPapelera@ButtonBehavior+Image>:
    source: "images/papelera.png"
    size_hint: None, None
    size: dp(50), dp(50)  # Cambiado a dp

<MyRoundedButton@Button>:
    background_normal: ""
    background_color: 0, 0, 0, 0
    canvas.before:
        Color:
            rgba: 0.121, 0.247, 0.376, 1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(20),]  # Cambiado a dp

<ButtonBehavior+Image>:
    source: "images/papelera.png"
    allow_stretch: True
    keep_ratio: True

<CarritoItemPago>:
    size_hint_y: None
    height: dp(55)

    BoxLayout:
        orientation: 'horizontal'
        padding: [dp(10), 0]
        spacing: dp(10)

        Label:
            id: label_descripcion
            font_name: 'Intro'
            font_size: sp(18)
            color: 0,0,0,1
            size_hint_x: 0.5
            halign: "left"
            valign: "middle"
            text_size: self.size

        Label:
            id: label_cantidad
            font_name: 'Intro'
            font_size: sp(18)
            color: 0,0,0,1
            size_hint_x: 0.2
            halign: "center"
            valign: "middle"
            text_size: self.size

        Label:
            id: label_total
            font_name: 'Intro'
            font_size: sp(18)
            color: 0,0,0,1
            size_hint_x: 0.3
            halign: "right"
            valign: "middle"
            text_size: self.size

<CarritoItem>:
    size_hint_y: None
    height: dp(60)  # Cambiado a dp

    BoxLayout:
        orientation: 'horizontal'
        spacing: dp(10)  # Cambiado a dp
        padding: [dp(10), dp(5)]  # Cambiado a dp

        Label:
            id: label_descripcion
            text: "Botellón - X L"
            font_name: 'Intro'
            font_size: sp(18)  # Cambiado a sp
            color: 0,0,0,1
            halign: "left"
            valign: "middle"
            text_size: (self.width, self.height)
            size_hint_x: 0.35

        # Contenedor de cantidad
        BoxLayout:
            orientation: 'horizontal'
            spacing: dp(5)  # Cambiado a dp
            size_hint_x: 0.23

            BotonOperacion2:
                img_src: "images/menos.png"
                size: dp(40), dp(40)
                on_press: root.decrementar_cantidad()

            Label:
                id: label_cantidad
                text: str(root.cantidad)
                font_name: 'Intro'
                font_size: sp(20)  # Cambiado a sp
                color: 0,0,0,1
                size_hint: None, None
                size: dp(40), dp(40)  # Cambiado a dp
                halign: "center"
                valign: "middle"
                text_size: (self.width, self.height)

            BotonOperacion2:
                img_src: "images/mas.png"
                size: dp(40), dp(40)
                on_press: root.aumentar_cantidad()
                
        Label:
            id: label_total
            text: f"Bs {root.total}"
            font_name: 'Intro'
            font_size: sp(20)
            color: 0,0,0,1
            size_hint_x: 0.30
            size_hint_y: None
            height: dp(40)
            halign: "center"
            valign: "middle"
            text_size: self.size
            
        BotonOperacion2:
            img_src: "images/papelera.png"
            size_hint: None, None
            size: dp(40), dp(40)  # Cambiado a dp
            on_press: root.eliminar_producto()
         
<GestorPantallas>:
    PantallaInicio:
    PantallaRecarga:
    PantallaInformacion:
    PantallaContacto:
    PantallaLogin:
    PantallaCarrito:

<PantallaInicio>:
    name: "inicio"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                source: "images/fondo.png"
                pos: self.pos
                size: self.size

        Image:
            source: "images/logo-inicio.png"
            size_hint: (0.8, 0.6)  # Ya está en proporciones relativas (correcto)
            pos_hint: {"center_x": 0.5, "top": 0.95}

        MyRoundedButton:
            text: "RECARGAR"
            font_name: 'Intro'
            font_size: sp(36)  # Cambiado a sp
            size_hint: (0.3, 0.15)  # Correcto (proporciones relativas)
            pos_hint: {"center_x": 0.5, "y": 0.2}
            color: (1, 1, 1, 1)
            on_press:
                app.root.current = "recarga"

        BotonImagen:
            id: superusuario
            source: "images/superusuario.png"
            pos_hint: {"right": 0.98, "top": 0.98}
            on_press: print("Superusuario")
            opacity: 0 #oculto al principio

        BotonImagen:
            source: "images/info.png"
            on_press: app.root.current = "informacion"
            pos_hint: {"x": 0.02, "y": 0.02}

        BotonImagen:
            source: "images/contacto.png"
            on_press: app.root.current = "contacto"
            pos_hint: {"right": 0.98, "y": 0.02}


<PantallaRecarga>:
    name: "recarga"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                source: "images/fondo.png"
                pos: self.pos
                size: self.size

        Label:
            text: "Seleccione la capacidad del botellón"
            font_name: 'Intro'
            font_size: sp(26)  # Cambiado a sp
            color: (0.110, 0.235, 0.392)
            size_hint: None, None
            size: self.texture_size
            pos_hint: {"center_x": 0.5, "center_y": 0.85}

        BotonImagen:
            id: carrito
            source: "images/carrito.png"
            size: dp(90), dp(70)  # Cambiado a dp
            pos_hint: {"right": 0.98, "top": 0.98}
            on_press:
                app.root.current = "carrito"

        # BOTONES PRODUCTOS  
        GridLayout:
            id: grid_botones
            cols: 5
            spacing: dp(30)  # Cambiado a dp
            size_hint: None, None
            size: dp(900), dp(150)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "center_y": 0.66}
            padding: 0

            BotonRecarga:
                img_src: "images/icono_1.png"
                text_btn: "1 Litro"
                pantalla_recarga: root
                on_press: root.seleccionar_producto(4)

            BotonRecarga:
                img_src: "images/icono_2.png"
                text_btn: "2 Litros"
                pantalla_recarga: root
                on_press: root.seleccionar_producto(3)

            BotonRecarga:
                img_src: "images/icono_5.png"
                text_btn: "5 Litros"
                pantalla_recarga: root
                on_press: root.seleccionar_producto(2)

            BotonRecarga:
                img_src: "images/icono_20.png"
                text_btn: "10 Litros"
                pantalla_recarga: root
                on_press: root.seleccionar_producto(1)

            BotonRecarga:
                img_src: "images/icono_10.png"
                text_btn: "19 Litros"
                pantalla_recarga: root
                on_press: root.seleccionar_producto(0)
        
        Label:
            text: "Indique la cantidad a recargar"
            font_name: 'Intro'
            font_size: sp(26)  # Cambiado a sp
            color: (0.110, 0.235, 0.392)
            size_hint: None, None
            size: self.texture_size
            pos_hint: {"center_x": 0.5, "top": 0.46}
        
        
        # CONTROLES CANTIDAD
        GridLayout:
            cols: 5
            spacing: dp(50)  # Cambiado a dp
            padding: dp(20)  # Cambiado a dp
            size_hint: None, None
            size: dp(870), dp(70)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "y": 0.29}

            Widget:

            BotonOperacion:
                img_src: "images/menos.png"
                on_press: root.decrementar_cantidad()

            Label:
                id: cantidad_label
                text: str(root.cantidad)
                font_size: sp(28)  # Cambiado a sp
                size_hint: None, None
                size: dp(70), dp(60)  # Cambiado a dp
                color: 0, 0, 0, 1
                canvas.before:
                    Color:
                        rgba: 0.9, 0.9, 0.9, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(15),]  # Cambiado a dp

            BotonOperacion:
                img_src: "images/mas.png"
                on_press: root.incrementar_cantidad()

            Widget:
        
        #BOTON AGREGAR
        GridLayout:
            cols: 5
            spacing: dp(50)  # Cambiado a dp
            padding: dp(20)  # Cambiado a dp
            size_hint: None, None
            size: dp(870), dp(70)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "y": 0.15}

            Widget:
            Widget:

            Button:
                text: "AÑADIR"
                font_name: 'Intro'
                font_size: sp(22)  # Cambiado a sp
                size_hint: None, None
                size: dp(150), dp(65)  # Cambiado a dp
                background_normal: ""
                background_color: 0, 0, 0, 0
                color: 1, 1, 1, 1
                canvas.before:
                    Color:
                        rgba: (0.027, 0.294, 0.541, 1) 
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(15),]  # Cambiado a dp
                on_press: root.agregar_al_carrito()

            Widget:
            Widget:

        Button:
            text: "REGRESAR"
            font_name: 'Intro'
            font_size: sp(22)  # Cambiado a sp
            size_hint: None, None
            size: dp(200), dp(65)  # Cambiado a dp
            pos_hint: {"x": 0.045, "y": 0.030}
            background_normal: ""
            background_color: 0, 0, 0, 0
            color: 1, 1, 1, 1
            canvas.before:
                Color:
                    rgba: rgba(151,2,2,255) # #971202
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(15),]  # Cambiado a dp
            on_press: app.root.current = "inicio"

    BoxLayout:
        orientation: 'vertical'
        size_hint: None, None
        size: (dp(300), dp(110))  # Cambiado a dp
        pos_hint: {'right': 0.65, 'y': 0.02}
        spacing: dp(8)  # Cambiado a dp

        Label:
            text: "Precio: ${} Bs".format(app.PRODUCTS[root.producto_seleccionado].precio)
            font_name: 'Intro'
            font_size: sp(18)  # Cambiado a sp
            color: (1.0, 1.0, 1.0)
            size_hint_y: None
            height: dp(40)  # Cambiado a dp


    Button:
        text: "CONTINUAR"
        font_name: 'Intro'
        font_size: sp(22)  # Cambiado a sp
        size_hint: None, None
        size: dp(200), dp(65)  # Cambiado a dp
        pos_hint: {'right': 0.95, 'y': 0.03}
        background_normal: ""
        background_color: 0, 0, 0, 0
        color: 1, 1, 1, 1
        canvas.before:
            Color:
                rgba: 0.118, 0.518, 0.286, 1 #1E8449
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [dp(15),]  # Cambiado a dp
        on_press: app.root.current = "carrito"

    #POPUP TEMPORAL (NOTIFICACION CARRITO)
    FloatLayout:
        size_hint: 1, 1
        BoxLayout:
            id: popup_label
            size_hint: None, None
            size: dp(400), dp(130)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            orientation: "vertical"
            spacing: dp(5)  # Cambiado a dp
            padding: [dp(20), dp(15)]  # Cambiado a dp
            opacity: 0
            canvas.before:
                Color:
                    rgba: 0.118, 0.518, 0.286, 0.7
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(20),]  # Cambiado a dp

            Image:
                source: "images/check.png" 
                size_hint: None, None
                size: dp(40), dp(40)  # Cambiado a dp
                pos_hint: {"center_x": 0.5}

            Label:
                text: "¡Producto agregado al carrito!"
                font_size: sp(20)  # Cambiado a sp
                font_name: 'Intro'
                color: 1, 1, 1, 1
                halign: "center"
                valign: "middle"
                text_size: self.size


<PantallaInformacion>:
    name: "informacion"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Image:
            source: "images/logo.png"
            size_hint: None, None
            size: dp(120), dp(100)  # Cambiado a dp
            pos_hint: {"x": 0.02, "top": 0.98}

        BoxLayout:
            orientation: "vertical"
            size_hint: 0.8, None
            height: self.minimum_height
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            Label:
                text: "Esta es una expendedora automatizada de agua.\nGracias por preferirnos."
                font_name: 'Intro'
                font_size: sp(24)  # Cambiado a sp
                halign: "center" 
                valign: "middle"
                color: 0, 0, 0, 1
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

        BotonVolver:
            pos_hint: {"x": 0.03, "y": 0.032}
            on_press:
                app.root.current = "inicio"

<PantallaContacto>:
    name: "contacto"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Image:
            source: "images/logo.png"
            size_hint: None, None
            size: dp(120), dp(100)  # Cambiado a dp
            pos_hint: {"x": 0.02, "top": 0.98}

        BoxLayout:
            orientation: "vertical"
            spacing: dp(10)  # Cambiado a dp
            size_hint: None, None
            size: dp(400), dp(300)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "center_y": 0.5}

            Image:
                source: "images/instagram.png"
                size_hint_y: None
                height: dp(50)  # Cambiado a dp
            Label:
                text: "Instagram: @example"
                font_name: 'Intro'
                font_size: sp(20)  # Cambiado a sp
                color: 0, 0, 0, 1

            Image:
                source: "images/correo.png"
                size_hint_y: None
                height: dp(50)  # Cambiado a dp
            Label:
                text: "Correo: example@example.com"
                font_name: 'Intro'
                font_size: sp(20)  # Cambiado a sp
                color: 0, 0, 0, 1

            Image:
                source: "images/telefono.png"
                size_hint_y: None
                height: dp(50)  # Cambiado a dp
            Label:
                text: "Teléfono: +1 234 567 890"
                font_name: 'Intro'
                font_size: sp(20)  # Cambiado a sp
                color: 0, 0, 0, 1

            Image:
                source: "images/whatsapp.png"
                size_hint_y: None
                height: dp(50)  # Cambiado a dp
            Label:
                text: "WhatsApp: +1 987 654 321"
                font_name: 'Intro'
                font_size: sp(20)  # Cambiado a sp
                color: 0, 0, 0, 1

        BotonVolver:
            pos_hint: {"x": 0.03, "y": 0.032}
            on_press:
                app.root.current = "inicio"


<PantallaLogin>:
    name: "login"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Image:
            source: "images/logo.png"
            size_hint: None, None
            size: dp(120), dp(100)  # Cambiado a dp
            pos_hint: {"x": 0.02, "top": 0.98}

        Image:
            source: "images/superusuario.png"
            size_hint: None, None
            size: dp(100), dp(100)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "top": 0.75}

        Label:
            text: "Modo Administrador"
            font_name: 'Intro'
            font_size: sp(28)  # Cambiado a sp
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.5, "top": 0.55}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: input_password
            password: True
            hint_text: "Contraseña"
            size_hint: None, None
            size: dp(300), dp(50)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "center_y": 0.42}
            font_name: 'Intro'
            font_size: sp(22)  # Cambiado a sp
            multiline: False

        Button:
            text: "Ingresar"
            font_name: 'Intro'
            font_size: sp(22)  # Cambiado a sp
            size_hint: None, None
            size: dp(300), dp(50)  # Cambiado a dp
            pos_hint: {"center_x": 0.5, "center_y": 0.32}
            background_normal: ""
            background_color: (0.121, 0.247, 0.376, 1)
            color: 1, 1, 1, 1
            on_press: root.verificar_contraseña()

        Label:
            id: etiqueta_status
            text: ""
            font_name: 'Intro'
            font_size: sp(18)  # Cambiado a sp
            color: (1, 0, 0, 1)
            pos_hint: {"center_x": 0.5, "center_y": 0.18}
            size_hint: None, None
            size: self.texture_size

        BotonVolver:
            pos_hint: {"x": 0.03, "y": 0.032}
            on_press:
                app.root.current = "inicio"

<PantallaCarrito>:
    name: "carrito"
    id: carrito_screen

    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                source: "images/fondo.png"
                pos: self.pos
                size: self.size

        # Título
        Label:
            text: "CARRITO DE COMPRA"
            font_name: 'Intro'
            font_size: sp(28)  # Cambiado a sp
            color: (0.110, 0.235, 0.392)
            size_hint: None, None
            size: self.texture_size
            pos_hint: {"center_x": 0.5, "top": 0.90}

        #Contenedor principal
        BoxLayout:
            orientation: 'vertical'
            size_hint: None, None
            size: self.parent.width * 0.6, self.parent.height * 0.65
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            padding: dp(5)  # Cambiado a dp
            spacing: dp(5)  # Cambiado a dp

            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(20),]  # Cambiado a dp
                Color:
                    rgba: app.azul_oscuro
                Line:
                    width: dp(1.8)  # Cambiado a dp
                    rounded_rectangle: (self.x, self.y, self.width, self.height, dp(20))  # Cambiado a dp

            #Encabezado de columnas
            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: None
                height: dp(30)  # Cambiado a dp
                spacing: dp(2)  # Cambiado a dp
                padding: [dp(10), 0, dp(10), 0]  # Cambiado a dp

                Label:
                    text: "PRODUCTO"
                    font_name: 'Intro'
                    font_size: sp(20)  # Cambiado a sp
                    color: 0, 0, 0, 1
                    bold: True
                    size_hint_x: 0.5
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    text: "CANTIDAD"
                    font_name: 'Intro'
                    font_size: sp(20)  # Cambiado a sp
                    color: 0, 0, 0, 1
                    bold: True
                    size_hint_x: 0.45
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    text: "MONTO"
                    font_name: 'Intro'
                    font_size: sp(20)  # Cambiado a sp
                    color: 0, 0, 0, 1
                    bold: True
                    size_hint_x: 0.35
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    text: ""
                    size_hint_x: 0.05
            
            #Divisor azul
            BoxLayout:
                size_hint_y: None
                height: dp(2)  # Cambiado a dp
                canvas.before:
                    Color:
                        rgba: app.azul_oscuro
                    Rectangle:
                        pos: self.pos
                        size: self.size

            # ScrollView con los CarritoItem
            ScrollView:
                size_hint_y: 1
                bar_width: dp(10)  # Cambiado a dp
                scroll_type: ['bars', 'content']
                do_scroll_x: False  

                GridLayout:
                    id: contenedor_items
                    cols: 1
                    spacing: dp(5)  # Cambiado a dp
                    padding: [dp(5), dp(5)]  # Cambiado a dp
                    size_hint_y: None
                    height: self.minimum_height
                    size_hint_x: 1
            
            #Divisor azul entre items y total
            BoxLayout:
                size_hint_y: None
                height: dp(2)  # Cambiado a dp
                canvas.before:
                    Color:
                        rgba: app.azul_oscuro
                    Rectangle:
                        pos: self.pos
                        size: self.size

            BoxLayout:
                size_hint_y: None
                height: dp(40)  # Cambiado a dp
                padding: [dp(10), 0, dp(10), 0]  # Cambiado a dp
                spacing: dp(10)  # Cambiado a dp

                Label:
                    text: "Total:"
                    font_name: 'Intro'
                    font_size: sp(20)  # Cambiado a sp
                    color: 0, 0, 0, 1
                    bold: True
                    halign: "left"
                    valign: "middle"
                    size_hint_x: 0.7
                    text_size: self.size

                Label:
                    id: total_label
                    text: "$0"
                    font_name: 'Intro'
                    font_size: sp(20)  # Cambiado a sp
                    color: 0, 0, 0, 1
                    halign: "right"
                    valign: "middle"
                    size_hint_x: 0.3
                    text_size: self.size

        Button:
            text: "PAGAR"
            font_name: 'Intro'
            font_size: sp(36)  # Cambiado a sp
            size_hint: (0.25, 0.10)
            pos_hint: {"center_x": 0.5, "y": 0.05}
            background_normal: ""
            background_color: 0, 0, 0, 0
            color: 1, 1, 1, 1
            canvas.before:
                Color:
                    rgba: 0.118, 0.518, 0.286, 1 #1E8449
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(15),]  # Cambiado a dp
            on_press: 
                root.imprimir_carrito()
                app.open_ticket()
                
        Button:
            text: "REGRESAR"
            font_name: 'Intro'
            font_size: sp(18)  # Cambiado a sp
            size_hint: None, None
            size: dp(150), dp(50)  # Cambiado a dp
            pos_hint: {"x": 0.03, "y": 0.032}
            background_normal: ""
            background_color: 0, 0, 0, 0
            color: 1, 1, 1, 1
            canvas.before:
                Color:
                    rgba: rgba(151,2,2,255) # #971202
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(15),]  # Cambiado a dp
            on_press: app.root.current = "recarga"

<CustomSpinnerDropdown@DropDown>:
    canvas.before:
        Color:
            rgba: app.azul_oscuro
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(15)]

<CustomSpinnerOption@SpinnerOption>:
    font_name: 'Intro'
    font_size: sp(16)
    color: 1, 1, 1, 1

    background_normal: ""
    background_down: ""
    background_color:
        (0.2, 0.6, 1, 1) if self.state == 'down' else app.azul_oscuro

<ModalTicketPago@FloatLayout>:  
    size_hint: None, None
    size: dp(600), dp(500)

    canvas.before:
        Color:
            rgba: 0, 0, 0, 0 
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(10)
        size_hint: None, None
        size: dp(600), dp(500)
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

        canvas.before:
            Color:
                rgba: 1,1,1,1  # fondo blanco del modal
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [dp(15)]  # esquinas redondeadas

        Label:
            text: "Ticket de Compra"
            font_name: 'Intro'
            bold: True
            font_size: sp(24)
            size_hint_y: None
            height: dp(40)
            color: 0, 0, 0, 1
            halign: "center"
            valign: "middle"
            text_size: self.size

        BoxLayout:
            orientation: 'vertical'
            spacing: dp(5)
            padding: dp(10)
            size_hint_y: None
            height: dp(350)
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(20),]
                Color:
                    rgba: app.azul_oscuro
                Line:
                    width: dp(1.5)
                    rounded_rectangle: (self.x, self.y, self.width, self.height, dp(20))

            BoxLayout:
                size_hint_y: None
                height: dp(30)
                spacing: dp(5)
                padding: [dp(10), 0, dp(10), 0]

                Label:
                    text: "PRODUCTO"
                    bold: True
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                    size_hint_x: 0.5
                    color: 0, 0, 0, 1
                    font_name: 'Intro'
                    font_size: sp(18)

                Label:
                    text: "CANTIDAD"
                    bold: True
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                    size_hint_x: 0.25
                    color: 0, 0, 0, 1
                    font_name: 'Intro'
                    font_size: sp(18)

                Label:
                    text: "MONTO"
                    bold: True
                    halign: "right"
                    valign: "middle"
                    text_size: self.size
                    size_hint_x: 0.25
                    color: 0, 0, 0, 1
                    font_name: 'Intro'
                    font_size: sp(18)

            BoxLayout:
                size_hint_y: None
                height: dp(2)
                canvas.before:
                    Color:
                        rgba: app.azul_oscuro
                    Rectangle:
                        pos: self.pos
                        size: self.size

            ScrollView:
                size_hint_y: 1
                do_scroll_x: False
                bar_width: dp(10)

                GridLayout:
                    id: contenedor_items
                    cols: 1
                    spacing: dp(5)
                    padding: dp(5)
                    size_hint_y: None
                    height: self.minimum_height

            BoxLayout:
                size_hint_y: None
                height: dp(2)
                canvas.before:
                    Color:
                        rgba: app.azul_oscuro
                    Rectangle:
                        pos: self.pos
                        size: self.size

            BoxLayout:
                size_hint_y: None
                height: dp(40)
                padding: [dp(10), 0, dp(10), 0]
                spacing: dp(10)

                Label:
                    text: "Total:"
                    bold: True
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                    size_hint_x: 0.7
                    color: 0, 0, 0, 1
                    font_name: 'Intro'
                    font_size: sp(18)

                Label:
                    id: total_label
                    text: "0 Bs"
                    halign: "right"
                    valign: "middle"
                    text_size: self.size
                    size_hint_x: 0.3
                    color: 0, 0, 0, 1
                    font_name: 'Intro'

        BoxLayout:
            size_hint_y: None
            height: dp(60)
            padding: [dp(10), 0, dp(10), 0]

            Button:
                text: "CANCELAR"
                font_name: 'Intro'
                font_size: sp(18)
                size_hint: None, None
                size: dp(150), dp(50)
                background_normal: ""
                background_color: 0, 0, 0, 0
                color: 1, 1, 1, 1
                canvas.before:
                    Color:
                        rgba: 0.588, 0.008, 0.008, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(15),]
                on_press: root.dismiss()

            Widget:  # Empuja los botones a los extremos
                size_hint_x: 1

            Button:
                text: "SIGUIENTE"
                font_name: 'Intro'
                font_size: sp(24)
                size_hint: None, None
                size: dp(150), dp(50)
                background_normal: ""
                background_color: 0, 0, 0, 0
                color: 1, 1, 1, 1
                canvas.before:
                    Color:
                        rgba: 0.118, 0.518, 0.286, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(15),]
                on_press: root.ir_a_pago()

<SpinnerOptionCustom@SpinnerOption>:
    font_name: 'Intro'
    font_size: sp(16)
    color: 1,1,1,1
    background_normal: ""
    background_color: 0,0,0,0
    size_hint_y: None
    height: dp(40)

    canvas.before:
        Color:
            rgba: app.azul_oscuro
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(12)]


<ModalConfirmarPago>:
    size_hint: None, None
    size: dp(600), dp(420)
    auto_dismiss: False
    background_color: 0,0,0,0

    FloatLayout:
        BoxLayout:
            orientation: 'vertical'
            size_hint: None, None
            size: root.size
            pos: root.pos
            padding: [dp(20), dp(5), dp(20), dp(10)]
            spacing: dp(10)

            canvas.before:
                Color:
                    rgba: 1,1,1,1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(15)]

            Label:
                text: "DATOS DE PAGO"
                size_hint_y: None
                height: dp(40)
                font_size: sp(20)
                bold: True
                font_name: 'Intro'
                color: 0,0,0,1

            Widget:
                size_hint_y: None
                height: dp(2)
                canvas:
                    Color:
                        rgba: app.azul_oscuro
                    Rectangle:
                        pos: self.pos
                        size: self.size

            BoxLayout:
                size_hint_y: None
                height: dp(45)
                spacing: dp(10)

                Label:
                    text: "Método de pago :"
                    font_name: 'Intro'
                    font_size: sp(16)
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size
                    color: 0,0,0,1

                Button:
                    text: "TARJETA"
                    size_hint: None, None
                    size: dp(240), dp(45)
                    background_normal: ""
                    background_color: 0,0,0,0
                    color: 1,1,1,1
                    font_name: 'Intro'
                    font_size: sp(20)
                    canvas.before:
                        Color:
                            rgba: app.azul_oscuro
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(15)]

            BoxLayout:
                id: box_tarjeta
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(10)

                BoxLayout:
                    size_hint_y: None
                    height: dp(45)
                    spacing: dp(10)

                    Label:
                        text: "CÉDULA :"
                        size_hint_x: 0.35
                        font_name: 'Intro'
                        font_size: sp(16)
                        halign: 'left'
                        valign: 'middle'
                        text_size: self.size
                        color: 0,0,0,1

                    TextInput:
                        id: input_cedula_tarjeta
                        multiline: False
                        input_filter: 'int'
                        keyboard_mode: 'managed'
                        keyboard: None
                        on_focus: root.focus_input(self, self.focus)
                        padding: dp(12), dp(12)
                        size_hint_x: None
                        width: dp(240)
                        background_normal: ""
                        background_active: ""
                        foreground_color: 0,0,0,1
                        cursor_color: 0,0,0,1
                        canvas.before:
                            Color:
                                rgba: 1,1,1,0.3
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [dp(15)]
                            Color:
                                rgba: app.azul_oscuro[0], app.azul_oscuro[1], app.azul_oscuro[2], 0.5
                            Line:
                                width: dp(1)
                                rounded_rectangle: (self.x, self.y, self.width, self.height, dp(15))

                BoxLayout:
                    size_hint_y: None
                    height: dp(45)
                    spacing: dp(10)

                    Label:
                        text: "CONTRASEÑA :"
                        size_hint_x: 0.35
                        font_name: 'Intro'
                        font_size: sp(16)
                        halign: 'left'
                        valign: 'middle'
                        text_size: self.size
                        color: 0,0,0,1

                    TextInput:
                        id: input_contrasena
                        password: True
                        multiline: False
                        input_filter: 'int'
                        keyboard_mode: 'managed'
                        keyboard: None
                        on_focus: root.focus_input(self, self.focus)
                        padding: dp(12), dp(12)
                        size_hint_x: None
                        width: dp(240)
                        background_normal: ""
                        background_active: ""
                        foreground_color: 0,0,0,1
                        cursor_color: 0,0,0,1
                        canvas.before:
                            Color:
                                rgba: 1,1,1,0.3
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [dp(15)]
                            Color:
                                rgba: app.azul_oscuro[0], app.azul_oscuro[1], app.azul_oscuro[2], 0.5
                            Line:
                                width: dp(1)
                                rounded_rectangle: (self.x, self.y, self.width, self.height, dp(15))

                BoxLayout:
                    size_hint_y: None
                    height: dp(45)
                    spacing: dp(10)

                    Label:
                        text: "Tipo de cuenta :"
                        size_hint_x: 0.35
                        font_name: 'Intro'
                        font_size: sp(16)
                        halign: 'left'
                        valign: 'middle'
                        text_size: self.size
                        color: 0,0,0,1

                    Spinner:
                        id: spinner_tipo_cuenta
                        text: "Corriente"
                        values: ["Corriente", "Ahorro"]
                        size_hint_x: None
                        width: dp(240)
                        background_normal: ""
                        background_color: 1,1,1,0.3
                        color: 0,0,0,1
                        font_name: 'Intro'
                        font_size: sp(16)
                        option_cls: 'SpinnerOptionCustom'
                        canvas.before:
                            Color:
                                rgba: 1,1,1,0.3
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [dp(15)]
                            Color:
                                rgba: app.azul_oscuro[0], app.azul_oscuro[1], app.azul_oscuro[2], 0.5
                            Line:
                                width: dp(1)
                                rounded_rectangle: (self.x, self.y, self.width, self.height, dp(15))

            Widget:
                size_hint_y: 1

            Widget:
                size_hint_y: None
                height: dp(2)
                canvas:
                    Color:
                        rgba: app.azul_oscuro
                    Rectangle:
                        pos: self.pos
                        size: self.size

            BoxLayout:
                size_hint_y: None
                height: dp(60)
                padding: [dp(10), 0, dp(10), 0]
                spacing: dp(10)

                Button:
                    text: "CANCELAR"
                    font_name: 'Intro'
                    font_size: sp(20)
                    size_hint: None, None
                    size: dp(150), dp(50)
                    background_normal: ""
                    background_color: 0,0,0,0
                    color: 1,1,1,1
                    canvas.before:
                        Color:
                            rgba: 0.588, 0.008, 0.008, 1
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(15)]
                    on_press: root.dismiss()

                Widget:
                    size_hint_x: 1

                Button:
                    text: "CONFIRMAR"
                    font_name: 'Intro'
                    font_size: sp(20)
                    size_hint: None, None
                    size: dp(150), dp(50)
                    background_normal: ""
                    background_color: 0,0,0,0
                    color: 1,1,1,1
                    canvas.before:
                        Color:
                            rgba: 0.118, 0.518, 0.286, 1
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(15)]
                    on_press: root.confirmar_pago()

        FloatLayout:
            id: keyboard_overlay
            size_hint: None, None
            size: dp(360), dp(300)
            pos_hint: {"center_x": 0.5, "center_y": 0.2}
            opacity: 0
            disabled: True

            BoxLayout:
                id: numeric_keyboard_container
                size_hint: None, None
                size: dp(360), dp(300)
                pos: 0,0
                orientation: 'vertical'
                padding: dp(10)


<ModalInstruccionesBotellon>:
    size_hint: None, None
    size: dp(720), dp(560)
    auto_dismiss: False

    FloatLayout:
        BoxLayout:
            orientation: "vertical"
            padding: [dp(20), dp(10), dp(20), dp(10)]
            spacing: dp(4)
            size_hint: None, None
            size: dp(720), dp(560)
            pos_hint: {"center_x": 0.5, "center_y": 0.5}

            canvas.before:
                Color:
                    rgba: 1,1,1,1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(20)]

            Label:
                id: titulo
                font_name: 'Intro'
                font_size: sp(22)
                halign: "center"
                valign: "middle"
                text_size: self.size
                size_hint_y: None
                height: dp(50)
                color: 0,0,0,1

            Widget:
                size_hint_y: None
                height: dp(2)
                canvas:
                    Color:
                        rgba: app.azul_oscuro
                    Rectangle:
                        pos: self.pos
                        size: self.size

            Image:
                source: "images/instrucciones_botellon.png"
                size_hint_x: None
                size_hint_y: 1
                width: dp(450)
                allow_stretch: True
                keep_ratio: True
                pos_hint: {"center_x": 0.5}

            Widget:
                size_hint_y: None
                height: dp(2)
                canvas:
                    Color:
                        rgba: app.azul_oscuro
                    Rectangle:
                        pos: self.pos
                        size: self.size
            Label:
                id: label_restantes
                font_name: 'Intro'
                font_size: sp(18)
                halign: "center"
                color: 0,0,0,1
                size_hint_y: None
                height: dp(32)


            BoxLayout:
                size_hint_y: None
                height: dp(80)

                BoxLayout:
                    orientation: "vertical"
                    size_hint_x: 0.5
                    spacing: dp(10)

                    Button:
                        id: btn_lavado
                        text: "LAVADO"
                        size_hint: None, None
                        size: dp(150), dp(50)
                        background_normal: ""
                        background_color: 0,0,0,0
                        color: 1,1,1,1
                        font_name: 'Intro'
                        font_size: sp(20)
                        on_press: root.iniciar_lavado()

                        canvas.before:
                            Color:
                                rgba: app.azul_oscuro if not self.disabled else (0.6,0.6,0.6,1)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [dp(15)]

                    Button:
                        id: btn_llenado
                        text: "LLENADO"
                        disabled: True
                        size_hint: None, None
                        size: dp(150), dp(50)
                        background_normal: ""
                        background_color: 0,0,0,0
                        color: 1,1,1,1
                        font_name: 'Intro'
                        font_size: sp(20)
                        on_press: root.iniciar_llenado()

                        canvas.before:
                            Color:
                                rgba: app.azul_oscuro if not self.disabled else (0.6,0.6,0.6,1)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [dp(15)]

                Widget:

                Button:
                    id: btn_continuar
                    text: "CONTINUAR"
                    disabled: True
                    size_hint: None, None
                    size: dp(150), dp(50)
                    font_name: 'Intro'
                    font_size: sp(24)
                    background_normal: ""
                    background_color: 0,0,0,0
                    color: 1,1,1,1
                    on_press: root.continuar()

                    canvas.before:
                        Color:
                            rgba: (0.118, 0.518, 0.286, 1) if not self.disabled else (0.6,0.6,0.6,1)
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(15)]

        # ---------- POPUP LAVADO ----------
        BoxLayout:
            id: popup_lavado
            size_hint: None, None
            size: dp(400), dp(150)
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            orientation: "vertical"
            spacing: dp(10)
            padding: [dp(20), dp(15)]
            opacity: 0

            canvas.before:
                Color:
                    rgba: 0.118, 0.518, 0.286, 0.7
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(20)]

            Image:
                source: "images/advertencia.png"
                size_hint: None, None
                size: dp(40), dp(40)
                pos_hint: {"center_x": 0.5}

            Label:
                text: "No mueva el botellón durante el lavado"
                font_size: sp(20)
                font_name: 'Intro'
                color: 1,1,1,1
                halign: "center"
                valign: "middle"
                text_size: self.size

            ProgressBar:
                id: barra_lavado
                max: 100
                value: 0
                size_hint_y: None
                height: dp(20)
                canvas.after:
                    Color:
                        rgba: 1,1,1,1
                    Rectangle:
                        pos: self.pos
                        size: (self.width * (self.value / self.max), self.height)

